# coding: utf-8

"""
    Visier System Status APIs

    Visier APIs for checking the health and status of Visier's platform and services.

    The version of the OpenAPI document: 22222222.99201.1389
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from visier.api.system_status.api.system_status_api import SystemStatusApi


class TestSystemStatusApi(unittest.TestCase):
    """SystemStatusApi unit test stubs"""

    def setUp(self) -> None:
        self.api = SystemStatusApi()

    def tearDown(self) -> None:
        pass

    def test_get_system_status_system_status(self) -> None:
        """Test case for get_system_status_system_status

        Check the overall current status of Visier's systems
        """
        pass

    def test_post_system_status_system_status(self) -> None:
        """Test case for post_system_status_system_status

        Check the overall current status of Visier's systems
        """
        pass


if __name__ == '__main__':
    unittest.main()
