# coding: utf-8

"""
    Visier Public Platform APIs

    Visier APIs for querying data and model metadata

    The version of the OpenAPI document: 22222222.99201.1081
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from visier.model_query.models.cell_set_axis_dto import CellSetAxisDTO

class TestCellSetAxisDTO(unittest.TestCase):
    """CellSetAxisDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CellSetAxisDTO:
        """Test CellSetAxisDTO
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CellSetAxisDTO`
        """
        model = CellSetAxisDTO()
        if include_optional:
            return CellSetAxisDTO(
                dimension = visier.model_query.models.dimension_reference_dto.DimensionReferenceDTO(
                    name = '', 
                    qualifying_path = '', ),
                positions = [
                    visier.model_query.models.cell_set_axis_position_dto.CellSetAxisPositionDTO(
                        path = [
                            ''
                            ], 
                        display_name = '', 
                        display_name_path = [
                            ''
                            ], )
                    ]
            )
        else:
            return CellSetAxisDTO(
        )
        """

    def testCellSetAxisDTO(self):
        """Test CellSetAxisDTO"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
