# coding: utf-8

"""
    Visier Public Platform APIs

    Visier APIs for querying data and model metadata

    The version of the OpenAPI document: 22222222.99201.1081
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from visier.model_query.models.planning_models_dto import PlanningModelsDTO

class TestPlanningModelsDTO(unittest.TestCase):
    """PlanningModelsDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PlanningModelsDTO:
        """Test PlanningModelsDTO
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PlanningModelsDTO`
        """
        model = PlanningModelsDTO()
        if include_optional:
            return PlanningModelsDTO(
                models = [
                    visier.model_query.models.planning_model_dto.PlanningModelDTO(
                        id = '', 
                        display_name = '', 
                        description = '', )
                    ]
            )
        else:
            return PlanningModelsDTO(
        )
        """

    def testPlanningModelsDTO(self):
        """Test PlanningModelsDTO"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
