# coding: utf-8

"""
    Visier Public Platform APIs

    Visier APIs for querying data and model metadata

    The version of the OpenAPI document: 22222222.99201.1081
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from visier.model_query.models.snapshot_query_execution_options_dto import SnapshotQueryExecutionOptionsDTO

class TestSnapshotQueryExecutionOptionsDTO(unittest.TestCase):
    """SnapshotQueryExecutionOptionsDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SnapshotQueryExecutionOptionsDTO:
        """Test SnapshotQueryExecutionOptionsDTO
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SnapshotQueryExecutionOptionsDTO`
        """
        model = SnapshotQueryExecutionOptionsDTO()
        if include_optional:
            return SnapshotQueryExecutionOptionsDTO(
                limit = 56,
                query_mode = 56,
                omit_header = True,
                calendar_type = 56,
                currency_conversion_date = '',
                page = 56,
                multiple_tables = True,
                currency_conversion_code = ''
            )
        else:
            return SnapshotQueryExecutionOptionsDTO(
        )
        """

    def testSnapshotQueryExecutionOptionsDTO(self):
        """Test SnapshotQueryExecutionOptionsDTO"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
