# coding: utf-8

"""
    Visier Authentication APIs

    Visier APIs for generating authentication tokens

    The version of the OpenAPI document: 22222222.99201.1081
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from visier.authentication.api.authentication_api import AuthenticationApi


class TestAuthenticationApi(unittest.TestCase):
    """AuthenticationApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AuthenticationApi()

    def tearDown(self) -> None:
        pass

    def test_authentication_asid_token_authentication(self) -> None:
        """Test case for authentication_asid_token_authentication

        """
        pass

    def test_authentication_o_auth2_authorize(self) -> None:
        """Test case for authentication_o_auth2_authorize

        """
        pass

    def test_authentication_o_auth2_token(self) -> None:
        """Test case for authentication_o_auth2_token

        """
        pass

    def test_authentication_ticket_authentication(self) -> None:
        """Test case for authentication_ticket_authentication

        """
        pass


if __name__ == '__main__':
    unittest.main()
