# coding: utf-8

# flake8: noqa
"""
    Visier Authentication APIs

    Visier API for requesting an authentication token through basic authentication.

    The version of the OpenAPI document: 22222222.99201.1371
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


# import models into model package
from visier.authentication.models.google_protobuf_any import GoogleProtobufAny
from visier.authentication.models.status import Status
from visier.authentication.models.token_response import TokenResponse
