generatorName: python
outputDir: $output_api_dir
templateDir: $templates_dir
inputSpec: $spec_file
packageName: $package_name
skipValidateSpec: true
enablePostProcessFile: true
gitHost: github.com
gitUserId: visier
gitRepoId: python-sdk
additionalProperties:
  packageVersion: $spec_version
  infoName: Visier
  infoEmail: alpine@visier.com
  licenseInfo: Apache-2.0
  hasAuthMethods: false
  allowEmptyValue: true