name: Generate API Documentation

on:
  pull_request:
    branches:
      - main
    types:
      - closed  # Trigger after a PR into main is closed
    paths:
      - 'res/**' # This will only trigger on changes to the /res/ folder
  workflow_dispatch:

jobs:
  generate-docs:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Add permissions for writing content (creating releases)

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install pyyaml
        pip install pytest

    - name: Run tests
      working-directory: redocly
      run: pytest

    - name: Install Redocly CLI
      run: npm install -g @redocly/cli

    - name: Generate API documentation with Redocly
      working-directory: redocly
      run: redocly build-docs ../res/visier-apis.yaml --template templates/redoc-template.html --output output/api-reference.htm

    - name: Run post-processing on generated documentation
      working-directory: redocly
      run: python ./scripts/api_reference_post_processing.py

    - name: Create tar.gz of HTML file
      run: |
        tar -czf redoc-static-${{ github.head_ref || github.ref_name }}.tar.gz -C redocly/output api-reference.htm

    - name: Create release
      id: create-release
      uses: ncipollo/release-action@v1
      with:
        tag: api-ref-${{ github.head_ref || github.ref_name }}
        name: "API Documentation - ${{ github.head_ref || github.ref_name }}"
        artifacts: redoc-static-${{ github.head_ref || github.ref_name }}.tar.gz
        omitBody: true
