name: Generate SDKs

on:
  workflow_dispatch:
    inputs:
      manual_openapi_client_pr_base_branch:
        description: |
          WARNING: Set this to the `main` branch for production releases!
          This workflow will create a Pull Request (PR) for the `openapi-clients` repository and merge it into the specified base branch.
        required: true
        type: string
        default: 'github-actions-test'
  push:
    branches:
      - 'release-**'

jobs:
  create-and-merge-pr:
    name: Create and Merge Pull Request for release
    runs-on: ubuntu-22.04
    permissions:
      contents: write
      pull-requests: write
    outputs:
      pr_number: ${{ steps.create_pr.outputs.pr_number }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Create a token
        id: create-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Create Pull Request for openapi-clients
        id: create_pr
        env:
          GH_TOKEN: ${{ steps.create-token.outputs.token }}
        run: |
          pr_output=$(gh pr create \
            --title "PR for ${{ github.ref_name }}" \
            --body "This PR created automatically after pushing changes to language-sdk repos." \
            --head "${{ github.ref_name }}" \
            --base "${{ github.event_name == 'workflow_dispatch' && github.event.inputs.manual_openapi_client_pr_base_branch || vars.OPENAPI_CLIENT_PR_BASE_BRANCH }}")
          pr_number=$(echo "$pr_output" | grep -oE '[0-9]+$')
          echo "Pull Request #$pr_number created successfully."
          echo "pr_number=$pr_number" >> $GITHUB_OUTPUT

      - name: Merge Pull Request
        env:
          GH_TOKEN: ${{ steps.create-token.outputs.token }}
        run: |
          gh pr merge ${{ steps.create_pr.outputs.pr_number }} \
            --squash \
            --delete-branch \
            --subject "Auto-merge: Update openapi"